server:
  host: 127.0.0.1
  port: 5000

application:
  title: DLCC
  app: dlcc.app:App
  authnz_provider: dlcc.baseapp.app:SQLAuthApp
  authn_storage: sqlstorage
  authn_policy: morpfw.auth.policy.jwtapikey:AuthnPolicy
  mounted_apps:
  - dlcc.baseapp.app:SQLAuthApp
  navigation:
  - section: General
    children:
    - title: Home
      icon: home
      children:
        - title: Home
          href: /
        - title: Profile
          href: /profile
  - section: Administrative
    children:
    - title: Settings
      icon: cog
      children:
        - title: Site
          href: /site-settings
        - title: Personal
          href: /personal-settings

beaker_session:
  session.cookie_expires: True
